### ISSUE TITLE
What's this? :)

### ISSUE THREAD

**Issue by steffenkrogmann** [GeorgeKihara/openupke-logic#2]

**Comment by steffenkrogmann** [comment]
@GeorgeKihara

**Comment by GeorgeKihara** [comment]
Hi @steffenkrogmann 
This is an app that will be used by the community to connect people suffering from mental disorders such as depression, anxiety, panic, among many others with therapists so that they can get help.

**Comment by steffenkrogmann** [comment]
Cool!
